In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import csv
import math
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [3]:
data_district = pd.read_csv("/content/drive/MyDrive/telangana/dim_districts.csv")
data_stamp = pd.read_csv("/content/drive/MyDrive/telangana/fact_stamps.csv")

In [4]:
data_district

   dist_code                 district
0       19_1                 Adilabad
1       22_2     Bhadradri Kothagudem
2       21_1              Hanumakonda
3       16_1                Hyderabad
4       20_2                  Jagtial
5       21_3                  Jangoan
6       21_7  Jayashankar Bhupalpally
7       14_2         Jogulamba Gadwal
8       18_2                Kamareddy
9       20_1               Karimnagar
10      22_1                  Khammam
11      19_4    Kumurambheem Asifabad
12      21_5              Mahabubabad
13      14_1             Mahabubnagar
14      19_3               Mancherial
15      17_1                    Medak
16      15_2       Medchal_Malkajgiri
17      21_6                   Mulugu
18      14_3             Nagarkurnool
19      23_1                 Nalgonda
20      14_5               Narayanpet
21      19_2                   Nirmal
22      18_1                Nizamabad
23      20_4               Peddapalli
24      20_3         Rajanna Sircilla
25      15_1               Rangareddy
26      17_2               Sangareddy
27      17_3                 Siddipet
28      23_2                 Suryapet
29      15_3                Vikarabad
30      14_4               Wanaparthy
31      21_2                 Warangal
32      23_3      Yadadri Bhuvanagiri

In [5]:
data_stamp

,dist_code,month,documents_registered_cnt,documents_registered_rev,estamps_challans_cnt,estamps_challans_rev
0,14_1,2019-04-01,4533,59236363,0,0
1,17_3,2019-04-01,4151,41508762,0,0
2,20_3,2019-04-01,2116,23674170,0,0
3,21_5,2019-04-01,1089,15915285,0,0
4,23_1,2019-04-01,6133,82593256,0,0
...,...,...,...,...,...,...
1499,20_4,2023-03-01,1510,54036552,1596,57171081
1500,14_5,2023-03-01,980,23898383,1026,23106330
1501,21_1,2023-03-01,4321,279791569,4642,284765300
1502,22_2,2023-03-01,1255,18695648,1566,22453502
1503,23_1,2023-03-01,5806,132022152,5997,135318190

In [6]:
data_stamp['district'] = data_stamp['dist_code'].map(data_district.set_index('dist_code')['district'])

In [7]:
data_stamp

,dist_code,month,documents_registered_cnt,documents_registered_rev,estamps_challans_cnt,estamps_challans_rev,district
0,14_1,2019-04-01,4533,59236363,0,0,Mahabubnagar
1,17_3,2019-04-01,4151,41508762,0,0,Siddipet
2,20_3,2019-04-01,2116,23674170,0,0,Rajanna Sircilla
3,21_5,2019-04-01,1089,15915285,0,0,Mahabubabad
4,23_1,2019-04-01,6133,82593256,0,0,Nalgonda
...,...,...,...,...,...,...,...
1499,20_4,2023-03-01,1510,54036552,1596,57171081,Peddapalli
1500,14_5,2023-03-01,980,23898383,1026,23106330,Narayanpet
1501,21_1,2023-03-01,4321,279791569,4642,284765300,Hanumakonda
1502,22_2,2023-03-01,1255,18695648,1566,22453502,Bhadradri Kothagudem
1503,23_1,2023-03-01,5806,132022152,5997,135318190,Nalgonda

In [8]:
column_to_move = 'district'
new_order = [column_to_move] + [col for col in data_stamp.columns if col != column_to_move]
data_stamp = data_stamp[new_order]
data_stamp

,district,dist_code,month,documents_registered_cnt,documents_registered_rev,estamps_challans_cnt,estamps_challans_rev
0,Mahabubnagar,14_1,2019-04-01,4533,59236363,0,0
1,Siddipet,17_3,2019-04-01,4151,41508762,0,0
2,Rajanna Sircilla,20_3,2019-04-01,2116,23674170,0,0
3,Mahabubabad,21_5,2019-04-01,1089,15915285,0,0
4,Nalgonda,23_1,2019-04-01,6133,82593256,0,0
...,...,...,...,...,...,...,...
1499,Peddapalli,20_4,2023-03-01,1510,54036552,1596,57171081
1500,Narayanpet,14_5,2023-03-01,980,23898383,1026,23106330
1501,Hanumakonda,21_1,2023-03-01,4321,279791569,4642,284765300
1502,Bhadradri Kothagudem,22_2,2023-03-01,1255,18695648,1566,22453502
1503,Nalgonda,23_1,2023-03-01,5806,132022152,5997,135318190

In [9]:
del data_stamp['dist_code']

In [10]:
data_stamp

,district,month,documents_registered_cnt,documents_registered_rev,estamps_challans_cnt,estamps_challans_rev
0,Mahabubnagar,2019-04-01,4533,59236363,0,0
1,Siddipet,2019-04-01,4151,41508762,0,0
2,Rajanna Sircilla,2019-04-01,2116,23674170,0,0
3,Mahabubabad,2019-04-01,1089,15915285,0,0
4,Nalgonda,2019-04-01,6133,82593256,0,0
...,...,...,...,...,...,...
1499,Peddapalli,2023-03-01,1510,54036552,1596,57171081
1500,Narayanpet,2023-03-01,980,23898383,1026,23106330
1501,Hanumakonda,2023-03-01,4321,279791569,4642,284765300
1502,Bhadradri Kothagudem,2023-03-01,1255,18695648,1566,22453502
1503,Nalgonda,2023-03-01,5806,132022152,5997,135318190

In [11]:
data_stamp_2 = data_stamp.copy(deep=True)

In [12]:
data_stamp_2

,district,month,documents_registered_cnt,documents_registered_rev,estamps_challans_cnt,estamps_challans_rev
0,Mahabubnagar,2019-04-01,4533,59236363,0,0
1,Siddipet,2019-04-01,4151,41508762,0,0
2,Rajanna Sircilla,2019-04-01,2116,23674170,0,0
3,Mahabubabad,2019-04-01,1089,15915285,0,0
4,Nalgonda,2019-04-01,6133,82593256,0,0
...,...,...,...,...,...,...
1499,Peddapalli,2023-03-01,1510,54036552,1596,57171081
1500,Narayanpet,2023-03-01,980,23898383,1026,23106330
1501,Hanumakonda,2023-03-01,4321,279791569,4642,284765300
1502,Bhadradri Kothagudem,2023-03-01,1255,18695648,1566,22453502
1503,Nalgonda,2023-03-01,5806,132022152,5997,135318190

In [13]:
data_stamp_2['month'] = pd.to_datetime(data_stamp_2['month'], format='%Y-%m-%d')

In [14]:
data_stamp_2

,district,month,documents_registered_cnt,documents_registered_rev,estamps_challans_cnt,estamps_challans_rev
0,Mahabubnagar,2019-04-01,4533,59236363,0,0
1,Siddipet,2019-04-01,4151,41508762,0,0
2,Rajanna Sircilla,2019-04-01,2116,23674170,0,0
3,Mahabubabad,2019-04-01,1089,15915285,0,0
4,Nalgonda,2019-04-01,6133,82593256,0,0
...,...,...,...,...,...,...
1499,Peddapalli,2023-03-01,1510,54036552,1596,57171081
1500,Narayanpet,2023-03-01,980,23898383,1026,23106330
1501,Hanumakonda,2023-03-01,4321,279791569,4642,284765300
1502,Bhadradri Kothagudem,2023-03-01,1255,18695648,1566,22453502
1503,Nalgonda,2023-03-01,5806,132022152,5997,135318190

In [15]:
# Filter data for the two financial years
fy_2021 = data_stamp_2[(data_stamp_2['month'] >= '2021-04-01') & (data_stamp_2['month'] <= '2022-03-31')]
fy_2022 = data_stamp_2[(data_stamp_2['month'] >= '2022-04-01') & (data_stamp_2['month'] <= '2023-03-31')]
fy_2019 = data_stamp_2[(data_stamp_2['month'] >= '2019-04-01') & (data_stamp_2['month'] <= '2020-03-31')]

In [16]:
fy_2022

,district,month,documents_registered_cnt,documents_registered_rev,estamps_challans_cnt,estamps_challans_rev
1120,Adilabad,2022-04-01,762,27857363,727,21849707
1121,Mahabubnagar,2022-04-01,3253,105448377,3285,105928140
1122,Kamareddy,2022-04-01,1592,40413483,1659,41078977
1123,Hyderabad,2022-04-01,4771,1211822842,5070,1178763492
1124,Jogulamba Gadwal,2022-04-01,1530,31200400,1593,31730285
...,...,...,...,...,...,...
1499,Peddapalli,2023-03-01,1510,54036552,1596,57171081
1500,Narayanpet,2023-03-01,980,23898383,1026,23106330
1501,Hanumakonda,2023-03-01,4321,279791569,4642,284765300
1502,Bhadradri Kothagudem,2023-03-01,1255,18695648,1566,22453502
1503,Nalgonda,2023-03-01,5806,132022152,5997,135318190

In [17]:
fy_2022_grouped = fy_2022.groupby('district').agg({
    'documents_registered_cnt': 'sum',
    'documents_registered_rev': 'sum',
    'estamps_challans_cnt': 'sum',
    'estamps_challans_rev': 'sum'
}).reset_index()

In [18]:
fy_2022_grouped

,district,documents_registered_cnt,documents_registered_rev,estamps_challans_cnt,estamps_challans_rev
0,Adilabad,11112,396840845,11559,390406044
1,Bhadradri Kothagudem,7231,292643450,7346,286343125
2,Hanumakonda,48326,2817238587,52167,2846856844
3,Hyderabad,63115,14266012441,68399,14374315032
4,Jagtial,19999,628898536,20368,635617022
5,Jangoan,18725,473726459,19407,485770112
6,Jogulamba Gadwal,16316,328969228,16785,331919414
7,Kamareddy,18527,471629404,19236,479194188
8,Karimnagar,33699,1550449161,34447,1555554043
9,Khammam,40135,1971647539,42181,2002220314
10,Kumurambheem Asifabad,2506,75231587,2497,75125612
11,Mahabubabad,16212,401471602,16917,402178710
12,Mahabubnagar,32028,1066013551,33076,1081759351
13,Mancherial,22345,648893681,23247,661727175
14,Medak,13361,694500305,13849,663813464
15,Medchal_Malkajgiri,162443,24043523530,170898,23596183308
16,Mulugu,10496,217697250,10841,220445520
17,Nagarkurnool,25765,500874055,26607,503243357
18,Nalgonda,51081,1370570095,52200,1378801930
19,Narayanpet,9757,260164500,10146,263221269
20,Nirmal,13814,338583662,14155,345679061
21,Nizamabad,45664,1441666957,47420,1449452877
22,Peddapalli,14518,610400730,14934,618663557
23,Rajanna Sircilla,20437,452637197,20584,455893155
24,Rangareddy,232668,37697750946,245168,38349357618
25,Sangareddy,71718,8273200321,74347,8259605302
26,Siddipet,44247,1007632858,40289,1016130830
27,Suryapet,34661,1025672569,35869,1025231495
28,Vikarabad,15373,513957911,15903,518763002
29,Wanaparthy,18836,437147289,19245,439781621
30,Warangal,9874,252278092,10258,251356586
31,Yadadri Bhuvanagiri,62084,2167480603,64616,2185270667

In [19]:
fy_2022_grouped['stamp_doc_ratio'] = ((fy_2022_grouped['estamps_challans_rev'] - fy_2022_grouped['documents_registered_rev']) / fy_2022_grouped['documents_registered_rev']) * 100

In [20]:
fy_2022_grouped

,district,documents_registered_cnt,documents_registered_rev,estamps_challans_cnt,estamps_challans_rev,stamp_doc_ratio
0,Adilabad,11112,396840845,11559,390406044,-1.621507
1,Bhadradri Kothagudem,7231,292643450,7346,286343125,-2.152901
2,Hanumakonda,48326,2817238587,52167,2846856844,1.051322
3,Hyderabad,63115,14266012441,68399,14374315032,0.759165
4,Jagtial,19999,628898536,20368,635617022,1.068294
5,Jangoan,18725,473726459,19407,485770112,2.542322
6,Jogulamba Gadwal,16316,328969228,16785,331919414,0.896797
7,Kamareddy,18527,471629404,19236,479194188,1.603968
8,Karimnagar,33699,1550449161,34447,1555554043,0.329252
9,Khammam,40135,1971647539,42181,2002220314,1.550621
10,Kumurambheem Asifabad,2506,75231587,2497,75125612,-0.140865
11,Mahabubabad,16212,401471602,16917,402178710,0.176129
12,Mahabubnagar,32028,1066013551,33076,1081759351,1.477073
13,Mancherial,22345,648893681,23247,661727175,1.977750
14,Medak,13361,694500305,13849,663813464,-4.418550
15,Medchal_Malkajgiri,162443,24043523530,170898,23596183308,-1.860544
16,Mulugu,10496,217697250,10841,220445520,1.262428
17,Nagarkurnool,25765,500874055,26607,503243357,0.473033
18,Nalgonda,51081,1370570095,52200,1378801930,0.600614
19,Narayanpet,9757,260164500,10146,263221269,1.174937
20,Nirmal,13814,338583662,14155,345679061,2.095612
21,Nizamabad,45664,1441666957,47420,1449452877,0.540064
22,Peddapalli,14518,610400730,14934,618663557,1.353673
23,Rajanna Sircilla,20437,452637197,20584,455893155,0.719331
24,Rangareddy,232668,37697750946,245168,38349357618,1.728503
25,Sangareddy,71718,8273200321,74347,8259605302,-0.164326
26,Siddipet,44247,1007632858,40289,1016130830,0.843360
27,Suryapet,34661,1025672569,35869,1025231495,-0.043003
28,Vikarabad,15373,513957911,15903,518763002,0.934919
29,Wanaparthy,18836,437147289,19245,439781621,0.602619
30,Warangal,9874,252278092,10258,251356586,-0.365274
31,Yadadri Bhuvanagiri,62084,2167480603,64616,2185270667,0.820772

In [21]:
fy_2021_grouped = fy_2021.groupby('district').agg({
    'documents_registered_cnt': 'sum',
    'documents_registered_rev': 'sum',
    'estamps_challans_cnt': 'sum',
    'estamps_challans_rev': 'sum'
}).reset_index()

In [22]:
fy_2021_grouped

,district,documents_registered_cnt,documents_registered_rev,estamps_challans_cnt,estamps_challans_rev
0,Adilabad,11031,324085539,13337,332597037
1,Bhadradri Kothagudem,9175,241537476,10261,254379427
2,Hanumakonda,42217,2077808629,46463,2112813388
3,Hyderabad,54277,10711890174,59519,10893677949
4,Jagtial,15698,440627967,16332,443715297
5,Jangoan,11756,259887134,12294,261658853
6,Jogulamba Gadwal,16735,272675969,17288,272076616
7,Kamareddy,19080,379949388,20062,380467770
8,Karimnagar,30547,1068655123,31737,1078423581
9,Khammam,44191,1643522261,46533,1644624288
10,Kumurambheem Asifabad,2321,61025705,2416,58294715
11,Mahabubabad,11685,257524461,12887,264393331
12,Mahabubnagar,30100,893998095,31260,899612434
13,Mancherial,16764,437644812,17847,444256231
14,Medak,9578,428017430,10126,482267731
15,Medchal_Malkajgiri,148290,18200892201,157552,18747892104
16,Mulugu,7841,147262077,8260,148856779
17,Nagarkurnool,24069,377760177,25012,378375339
18,Nalgonda,50882,1216066394,52572,1221278894
19,Narayanpet,8324,201723820,8699,205291521
20,Nirmal,14725,295357009,15156,293878065
21,Nizamabad,45051,1151056746,48861,1165209994
22,Peddapalli,13351,500011727,14270,508023769
23,Rajanna Sircilla,16463,291933827,16789,294316478
24,Rangareddy,221446,31865475990,235763,32332939769
25,Sangareddy,63764,6344385117,69505,6522436259
26,Siddipet,35496,734228894,36768,746741914
27,Suryapet,30738,777314773,32906,792850936
28,Vikarabad,14839,373227540,15486,387426499
29,Wanaparthy,17282,306686397,17997,306488316
30,Warangal,7885,174157126,8293,173457579
31,Yadadri Bhuvanagiri,58979,1619590278,61727,1616599565

In [23]:
data_stamp_2

,district,month,documents_registered_cnt,documents_registered_rev,estamps_challans_cnt,estamps_challans_rev
0,Mahabubnagar,2019-04-01,4533,59236363,0,0
1,Siddipet,2019-04-01,4151,41508762,0,0
2,Rajanna Sircilla,2019-04-01,2116,23674170,0,0
3,Mahabubabad,2019-04-01,1089,15915285,0,0
4,Nalgonda,2019-04-01,6133,82593256,0,0
...,...,...,...,...,...,...
1499,Peddapalli,2023-03-01,1510,54036552,1596,57171081
1500,Narayanpet,2023-03-01,980,23898383,1026,23106330
1501,Hanumakonda,2023-03-01,4321,279791569,4642,284765300
1502,Bhadradri Kothagudem,2023-03-01,1255,18695648,1566,22453502
1503,Nalgonda,2023-03-01,5806,132022152,5997,135318190

In [24]:
cols_needed = ['district', 'documents_registered_rev']
q1a = data_stamp_2[cols_needed]
q1a

                  district  documents_registered_rev
0             Mahabubnagar                  59236363
1                 Siddipet                  41508762
2         Rajanna Sircilla                  23674170
3              Mahabubabad                  15915285
4                 Nalgonda                  82593256
...                    ...                       ...
1499            Peddapalli                  54036552
1500            Narayanpet                  23898383
1501           Hanumakonda                 279791569
1502  Bhadradri Kothagudem                  18695648
1503              Nalgonda                 132022152

[1504 rows x 2 columns]

In [25]:
q1a = q1a.groupby('district').agg({
    'documents_registered_rev': 'sum'
}).reset_index()

In [26]:
q1a = q1a.sort_values(by='documents_registered_rev', ascending=False).reset_index(drop=True)
q1a

                 district  documents_registered_rev
0              Rangareddy              108198682809
1      Medchal_Malkajgiri               64071382839
2               Hyderabad               38396743983
3              Sangareddy               22024502771
4             Hanumakonda                7927494100
5     Yadadri Bhuvanagiri                5973744502
6                 Khammam                5606141586
7                Nalgonda                4521634367
8               Nizamabad                4046937361
9              Karimnagar                4024475054
10           Mahabubnagar                3186731550
11               Suryapet                2902358766
12               Siddipet                2625072577
13                  Medak                1765752735
14             Peddapalli                1740644457
15             Mancherial                1668092668
16                Jagtial                1666081307
17              Kamareddy                1396196267
18              Vikarabad                1381189602
19           Nagarkurnool                1358262744
20                Jangoan                1329898858
21       Rajanna Sircilla                1169030429
22             Wanaparthy                1126819540
23               Adilabad                1066971491
24            Mahabubabad                1058624771
25                 Nirmal                 988708614
26       Jogulamba Gadwal                 978779682
27   Bhadradri Kothagudem                 824712666
28               Warangal                 738341643
29             Narayanpet                 722273314
30                 Mulugu                 515528121
31  Kumurambheem Asifabad                 227462583

In [27]:
fy_2019_grouped = fy_2019.groupby('district').agg({
    'documents_registered_cnt': 'sum',
    'documents_registered_rev': 'sum',
    'estamps_challans_cnt': 'sum',
    'estamps_challans_rev': 'sum'
}).reset_index()

In [28]:
fy_2019_grouped

,district,documents_registered_cnt,documents_registered_rev,estamps_challans_cnt,estamps_challans_rev
0,Adilabad,12552,178082233,0,0
1,Bhadradri Kothagudem,7488,162466947,0,0
2,Hanumakonda,60748,1738280378,0,0
3,Hyderabad,62699,8299406278,0,0
4,Jagtial,28828,357209544,0,0
5,Jangoan,30800,409485414,0,0
6,Jogulamba Gadwal,25511,208150602,0,0
7,Kamareddy,37889,326137044,0,0
8,Karimnagar,41076,804402135,0,0
9,Khammam,58335,1128220987,0,0
10,Kumurambheem Asifabad,4956,57436107,0,0
11,Mahabubabad,16822,213431168,0,0
12,Mahabubnagar,51559,791024058,0,0
13,Mancherial,21877,338407605,0,0
14,Medak,29252,437471000,0,0
15,Medchal_Malkajgiri,161988,12543288516,0,0
16,Mulugu,8667,80349554,0,0
17,Nagarkurnool,40062,291578083,0,0
18,Nalgonda,81916,1059467757,0,0
19,Narayanpet,21595,159698783,0,0
20,Nirmal,20311,217776493,0,0
21,Nizamabad,60041,773731832,0,0
22,Peddapalli,21559,352755096,0,0
23,Rajanna Sircilla,26771,269532142,0,0
24,Rangareddy,308914,23249650199,0,0
25,Sangareddy,101454,4597623320,0,0
26,Siddipet,60489,558514685,0,0
27,Suryapet,41946,641163562,0,0
28,Vikarabad,26459,328589615,0,0
29,Wanaparthy,31180,231229730,0,0
30,Warangal,13954,186426808,0,0
31,Yadadri Bhuvanagiri,96719,1419786551,0,0

In [29]:
columns_to_select = ['district', 'documents_registered_rev']
q1b = pd.merge(fy_2019_grouped[columns_to_select], fy_2022_grouped[columns_to_select], on='district', how='outer')

In [30]:
q1b

,district,documents_registered_rev_x,documents_registered_rev_y
0,Adilabad,178082233,396840845
1,Bhadradri Kothagudem,162466947,292643450
2,Hanumakonda,1738280378,2817238587
3,Hyderabad,8299406278,14266012441
4,Jagtial,357209544,628898536
5,Jangoan,409485414,473726459
6,Jogulamba Gadwal,208150602,328969228
7,Kamareddy,326137044,471629404
8,Karimnagar,804402135,1550449161
9,Khammam,1128220987,1971647539
10,Kumurambheem Asifabad,57436107,75231587
11,Mahabubabad,213431168,401471602
12,Mahabubnagar,791024058,1066013551
13,Mancherial,338407605,648893681
14,Medak,437471000,694500305
15,Medchal_Malkajgiri,12543288516,24043523530
16,Mulugu,80349554,217697250
17,Nagarkurnool,291578083,500874055
18,Nalgonda,1059467757,1370570095
19,Narayanpet,159698783,260164500
20,Nirmal,217776493,338583662
21,Nizamabad,773731832,1441666957
22,Peddapalli,352755096,610400730
23,Rajanna Sircilla,269532142,452637197
24,Rangareddy,23249650199,37697750946
25,Sangareddy,4597623320,8273200321
26,Siddipet,558514685,1007632858
27,Suryapet,641163562,1025672569
28,Vikarabad,328589615,513957911
29,Wanaparthy,231229730,437147289
30,Warangal,186426808,252278092
31,Yadadri Bhuvanagiri,1419786551,2167480603

In [31]:
q1b = q1b.rename(columns={'documents_registered_rev_x': 'documents_registered_rev_2019'})
q1b = q1b.rename(columns={'documents_registered_rev_y': 'documents_registered_rev_2022'})
q1b

,district,documents_registered_rev_2019,documents_registered_rev_2022
0,Adilabad,178082233,396840845
1,Bhadradri Kothagudem,162466947,292643450
2,Hanumakonda,1738280378,2817238587
3,Hyderabad,8299406278,14266012441
4,Jagtial,357209544,628898536
5,Jangoan,409485414,473726459
6,Jogulamba Gadwal,208150602,328969228
7,Kamareddy,326137044,471629404
8,Karimnagar,804402135,1550449161
9,Khammam,1128220987,1971647539
10,Kumurambheem Asifabad,57436107,75231587
11,Mahabubabad,213431168,401471602
12,Mahabubnagar,791024058,1066013551
13,Mancherial,338407605,648893681
14,Medak,437471000,694500305
15,Medchal_Malkajgiri,12543288516,24043523530
16,Mulugu,80349554,217697250
17,Nagarkurnool,291578083,500874055
18,Nalgonda,1059467757,1370570095
19,Narayanpet,159698783,260164500
20,Nirmal,217776493,338583662
21,Nizamabad,773731832,1441666957
22,Peddapalli,352755096,610400730
23,Rajanna Sircilla,269532142,452637197
24,Rangareddy,23249650199,37697750946
25,Sangareddy,4597623320,8273200321
26,Siddipet,558514685,1007632858
27,Suryapet,641163562,1025672569
28,Vikarabad,328589615,513957911
29,Wanaparthy,231229730,437147289
30,Warangal,186426808,252278092
31,Yadadri Bhuvanagiri,1419786551,2167480603

In [32]:
q1b['documents_registered_rev_growth'] = ((q1b['documents_registered_rev_2022'] - q1b['documents_registered_rev_2019']) / q1b['documents_registered_rev_2019']) * 100
q1b

,district,documents_registered_rev_2019,documents_registered_rev_2022,documents_registered_rev_growth
0,Adilabad,178082233,396840845,122.841346
1,Bhadradri Kothagudem,162466947,292643450,80.124915
2,Hanumakonda,1738280378,2817238587,62.070436
3,Hyderabad,8299406278,14266012441,71.891964
4,Jagtial,357209544,628898536,76.058716
5,Jangoan,409485414,473726459,15.688238
6,Jogulamba Gadwal,208150602,328969228,58.043851
7,Kamareddy,326137044,471629404,44.610805
8,Karimnagar,804402135,1550449161,92.745530
9,Khammam,1128220987,1971647539,74.757212
10,Kumurambheem Asifabad,57436107,75231587,30.983089
11,Mahabubabad,213431168,401471602,88.103549
12,Mahabubnagar,791024058,1066013551,34.763733
13,Mancherial,338407605,648893681,91.749143
14,Medak,437471000,694500305,58.753450
15,Medchal_Malkajgiri,12543288516,24043523530,91.684370
16,Mulugu,80349554,217697250,170.937720
17,Nagarkurnool,291578083,500874055,71.780420
18,Nalgonda,1059467757,1370570095,29.364021
19,Narayanpet,159698783,260164500,62.909507
20,Nirmal,217776493,338583662,55.473007
21,Nizamabad,773731832,1441666957,86.326437
22,Peddapalli,352755096,610400730,73.038104
23,Rajanna Sircilla,269532142,452637197,67.934404
24,Rangareddy,23249650199,37697750946,62.143304
25,Sangareddy,4597623320,8273200321,79.945153
26,Siddipet,558514685,1007632858,80.412957
27,Suryapet,641163562,1025672569,59.970502
28,Vikarabad,328589615,513957911,56.413315
29,Wanaparthy,231229730,437147289,89.053237
30,Warangal,186426808,252278092,35.322862
31,Yadadri Bhuvanagiri,1419786551,2167480603,52.662427

In [33]:
q1b = q1b.sort_values(by='documents_registered_rev_growth', ascending=False).reset_index(drop=True)

In [34]:
q1b = q1b.head(5)
q1b

,district,documents_registered_rev_2019,documents_registered_rev_2022,documents_registered_rev_growth
0,Mulugu,80349554,217697250,170.937720
1,Adilabad,178082233,396840845,122.841346
2,Karimnagar,804402135,1550449161,92.745530
3,Mancherial,338407605,648893681,91.749143
4,Medchal_Malkajgiri,12543288516,24043523530,91.684370

In [35]:
q2a = data_stamp_2.copy(deep=True)
q2a

,district,month,documents_registered_cnt,documents_registered_rev,estamps_challans_cnt,estamps_challans_rev
0,Mahabubnagar,2019-04-01,4533,59236363,0,0
1,Siddipet,2019-04-01,4151,41508762,0,0
2,Rajanna Sircilla,2019-04-01,2116,23674170,0,0
3,Mahabubabad,2019-04-01,1089,15915285,0,0
4,Nalgonda,2019-04-01,6133,82593256,0,0
...,...,...,...,...,...,...
1499,Peddapalli,2023-03-01,1510,54036552,1596,57171081
1500,Narayanpet,2023-03-01,980,23898383,1026,23106330
1501,Hanumakonda,2023-03-01,4321,279791569,4642,284765300
1502,Bhadradri Kothagudem,2023-03-01,1255,18695648,1566,22453502
1503,Nalgonda,2023-03-01,5806,132022152,5997,135318190

In [36]:
q2a = q2a.groupby('district').agg({
    'documents_registered_cnt': 'sum',
    'documents_registered_rev': 'sum',
    'estamps_challans_cnt': 'sum',
    'estamps_challans_rev': 'sum'
}).reset_index()

In [37]:
del q2a['estamps_challans_cnt']
del q2a['documents_registered_cnt']
q2a

                 district  documents_registered_rev  estamps_challans_rev
0                Adilabad                1066971491             831038256
1    Bhadradri Kothagudem                 824712666             616009645
2             Hanumakonda                7927494100            5751116148
3               Hyderabad               38396743983           28652397786
4                 Jagtial                1666081307            1202617958
5                 Jangoan                1329898858             842885890
6        Jogulamba Gadwal                 978779682             709344353
7               Kamareddy                1396196267             982520443
8              Karimnagar                4024475054            2989066355
9                 Khammam                5606141586            4208231368
10  Kumurambheem Asifabad                 227462583             145692452
11            Mahabubabad                1058624771             779396646
12           Mahabubnagar                3186731550            2236920432
13             Mancherial                1668092668            1246862431
14                  Medak                1765752735            1250558303
15     Medchal_Malkajgiri               64071382839           48819368222
16                 Mulugu                 515528121             408743315
17           Nagarkurnool                1358262744             980926364
18               Nalgonda                4521634367            3009297574
19             Narayanpet                 722273314             517604092
20                 Nirmal                 988708614             707305113
21              Nizamabad                4046937361            3047094971
22             Peddapalli                1740644457            1271068835
23       Rajanna Sircilla                1169030429             825570704
24             Rangareddy              108198682809           81336993463
25             Sangareddy               22024502771           16708219605
26               Siddipet                2625072577            1947542406
27               Suryapet                2902358766            2092895272
28              Vikarabad                1381189602             995418682
29             Wanaparthy                1126819540             830193698
30               Warangal                 738341643             484464966
31    Yadadri Bhuvanagiri                5973744502            4254388510

In [38]:
q2a['stamp_doc_ratio'] = ((q2a['documents_registered_rev'] - q2a['estamps_challans_rev']) / q2a['documents_registered_rev']) * 100
q2a

,district,documents_registered_rev,estamps_challans_rev,stamp_doc_ratio
0,Adilabad,1066971491,831038256,22.112422
1,Bhadradri Kothagudem,824712666,616009645,25.306150
2,Hanumakonda,7927494100,5751116148,27.453542
3,Hyderabad,38396743983,28652397786,25.378053
4,Jagtial,1666081307,1202617958,27.817571
5,Jangoan,1329898858,842885890,36.620301
6,Jogulamba Gadwal,978779682,709344353,27.527679
7,Kamareddy,1396196267,982520443,29.628773
8,Karimnagar,4024475054,2989066355,25.727795
9,Khammam,5606141586,4208231368,24.935336
10,Kumurambheem Asifabad,227462583,145692452,35.948827
11,Mahabubabad,1058624771,779396646,26.376496
12,Mahabubnagar,3186731550,2236920432,29.805181
13,Mancherial,1668092668,1246862431,25.252208
14,Medak,1765752735,1250558303,29.177043
15,Medchal_Malkajgiri,64071382839,48819368222,23.804722
16,Mulugu,515528121,408743315,20.713672
17,Nagarkurnool,1358262744,980926364,27.780809
18,Nalgonda,4521634367,3009297574,33.446685
19,Narayanpet,722273314,517604092,28.336811
20,Nirmal,988708614,707305113,28.461722
21,Nizamabad,4046937361,3047094971,24.706149
22,Peddapalli,1740644457,1271068835,26.977113
23,Rajanna Sircilla,1169030429,825570704,29.379879
24,Rangareddy,108198682809,81336993463,24.826263
25,Sangareddy,22024502771,16708219605,24.138039
26,Siddipet,2625072577,1947542406,25.809960
27,Suryapet,2902358766,2092895272,27.889850
28,Vikarabad,1381189602,995418682,27.930338
29,Wanaparthy,1126819540,830193698,26.324166
30,Warangal,738341643,484464966,34.384716
31,Yadadri Bhuvanagiri,5973744502,4254388510,28.781880

In [39]:
q2b = fy_2022_grouped.copy(deep=True)
del q2b['estamps_challans_cnt']
del q2b['documents_registered_cnt']
q2b

,district,documents_registered_rev,estamps_challans_rev,stamp_doc_ratio
0,Adilabad,396840845,390406044,-1.621507
1,Bhadradri Kothagudem,292643450,286343125,-2.152901
2,Hanumakonda,2817238587,2846856844,1.051322
3,Hyderabad,14266012441,14374315032,0.759165
4,Jagtial,628898536,635617022,1.068294
5,Jangoan,473726459,485770112,2.542322
6,Jogulamba Gadwal,328969228,331919414,0.896797
7,Kamareddy,471629404,479194188,1.603968
8,Karimnagar,1550449161,1555554043,0.329252
9,Khammam,1971647539,2002220314,1.550621
10,Kumurambheem Asifabad,75231587,75125612,-0.140865
11,Mahabubabad,401471602,402178710,0.176129
12,Mahabubnagar,1066013551,1081759351,1.477073
13,Mancherial,648893681,661727175,1.977750
14,Medak,694500305,663813464,-4.418550
15,Medchal_Malkajgiri,24043523530,23596183308,-1.860544
16,Mulugu,217697250,220445520,1.262428
17,Nagarkurnool,500874055,503243357,0.473033
18,Nalgonda,1370570095,1378801930,0.600614
19,Narayanpet,260164500,263221269,1.174937
20,Nirmal,338583662,345679061,2.095612
21,Nizamabad,1441666957,1449452877,0.540064
22,Peddapalli,610400730,618663557,1.353673
23,Rajanna Sircilla,452637197,455893155,0.719331
24,Rangareddy,37697750946,38349357618,1.728503
25,Sangareddy,8273200321,8259605302,-0.164326
26,Siddipet,1007632858,1016130830,0.843360
27,Suryapet,1025672569,1025231495,-0.043003
28,Vikarabad,513957911,518763002,0.934919
29,Wanaparthy,437147289,439781621,0.602619
30,Warangal,252278092,251356586,-0.365274
31,Yadadri Bhuvanagiri,2167480603,2185270667,0.820772

In [40]:
q2b = q2b.sort_values(by='stamp_doc_ratio', ascending=False).reset_index(drop=True)
q2b = q2b.head(5)
q2b

     district  documents_registered_rev  estamps_challans_rev  stamp_doc_ratio
0     Jangoan                 473726459             485770112         2.542322
1      Nirmal                 338583662             345679061         2.095612
2  Mancherial                 648893681             661727175         1.977750
3  Rangareddy               37697750946           38349357618         1.728503
4   Kamareddy                 471629404             479194188         1.603968

In [41]:
q3 = data_stamp_2.copy(deep=True)
q3

,district,month,documents_registered_cnt,documents_registered_rev,estamps_challans_cnt,estamps_challans_rev
0,Mahabubnagar,2019-04-01,4533,59236363,0,0
1,Siddipet,2019-04-01,4151,41508762,0,0
2,Rajanna Sircilla,2019-04-01,2116,23674170,0,0
3,Mahabubabad,2019-04-01,1089,15915285,0,0
4,Nalgonda,2019-04-01,6133,82593256,0,0
...,...,...,...,...,...,...
1499,Peddapalli,2023-03-01,1510,54036552,1596,57171081
1500,Narayanpet,2023-03-01,980,23898383,1026,23106330
1501,Hanumakonda,2023-03-01,4321,279791569,4642,284765300
1502,Bhadradri Kothagudem,2023-03-01,1255,18695648,1566,22453502
1503,Nalgonda,2023-03-01,5806,132022152,5997,135318190

In [42]:
q3 = q3.groupby('month').agg({
    'documents_registered_cnt': 'sum',
    'documents_registered_rev': 'sum',
    'estamps_challans_cnt': 'sum',
    'estamps_challans_rev': 'sum'
}).reset_index()

In [43]:
del q3['documents_registered_rev']
del q3['estamps_challans_rev']
q3

        month  documents_registered_cnt  estamps_challans_cnt
0  2019-04-01                    130223                     0
1  2019-05-01                    144201                     0
2  2019-06-01                    133916                     0
3  2019-07-01                    158479                     0
4  2019-08-01                    144914                     0
5  2019-09-01                    131759                     0
6  2019-10-01                    125855                     0
7  2019-11-01                    122205                     0
8  2019-12-01                    140440                     0
9  2020-01-01                    120851                     0
10 2020-02-01                    149151                     0
11 2020-03-01                    112423                     0
12 2020-04-01                      4492                     0
13 2020-05-01                     73005                     0
14 2020-06-01                    136196                     0
15 2020-07-01                    126672                     0
16 2020-08-01                    104469                     0
17 2020-09-01                     23255                     0
18 2020-10-01                       480                     0
19 2020-11-01                       277                     0
20 2020-12-01                     47019                 54241
21 2021-01-01                    147889                153097
22 2021-02-01                    137407                140062
23 2021-03-01                    142732                148732
24 2021-04-01                    107210                111412
25 2021-05-01                     27510                 26502
26 2021-06-01                     93591                105664
27 2021-07-01                    123971                134441
28 2021-08-01                     95583                102364
29 2021-10-01                     95766                100475
30 2021-11-01                     96136                101484
31 2021-12-01                    118221                122275
32 2022-01-01                    124221                139513
33 2022-02-01                    101442                101456
34 2022-03-01                    120929                128392
35 2022-04-01                    106000                109522
36 2022-05-01                    104832                109611
37 2022-06-01                    102292                105970
38 2022-07-01                     95846                 98843
39 2022-08-01                     92401                 96768
40 2022-09-01                     98286                102162
41 2022-10-01                     83444                 86507
42 2022-11-01                    100526                105820
43 2022-12-01                    109515                111806
44 2023-01-01                     96256                102968
45 2023-02-01                    101647                104039
46 2023-03-01                    116028                120945

In [44]:
q4 = fy_2021_grouped.copy(deep=True)
del q4['estamps_challans_cnt']
del q4['documents_registered_cnt']
del q4['estamps_challans_rev']
q4

                 district  documents_registered_rev
0                Adilabad                 324085539
1    Bhadradri Kothagudem                 241537476
2             Hanumakonda                2077808629
3               Hyderabad               10711890174
4                 Jagtial                 440627967
5                 Jangoan                 259887134
6        Jogulamba Gadwal                 272675969
7               Kamareddy                 379949388
8              Karimnagar                1068655123
9                 Khammam                1643522261
10  Kumurambheem Asifabad                  61025705
11            Mahabubabad                 257524461
12           Mahabubnagar                 893998095
13             Mancherial                 437644812
14                  Medak                 428017430
15     Medchal_Malkajgiri               18200892201
16                 Mulugu                 147262077
17           Nagarkurnool                 377760177
18               Nalgonda                1216066394
19             Narayanpet                 201723820
20                 Nirmal                 295357009
21              Nizamabad                1151056746
22             Peddapalli                 500011727
23       Rajanna Sircilla                 291933827
24             Rangareddy               31865475990
25             Sangareddy                6344385117
26               Siddipet                 734228894
27               Suryapet                 777314773
28              Vikarabad                 373227540
29             Wanaparthy                 306686397
30               Warangal                 174157126
31    Yadadri Bhuvanagiri                1619590278

In [45]:
q1a.to_csv('/content/drive/MyDrive/q1a.csv',index=False)

In [46]:
q1b.to_csv('/content/drive/MyDrive/q1b.csv',index=False)

In [47]:
q2a.to_csv('/content/drive/MyDrive/q2a.csv',index=False)

In [48]:
q2b.to_csv('/content/drive/MyDrive/q2b.csv',index=False)

In [49]:
q3.to_csv('/content/drive/MyDrive/q3.csv',index=False)

In [50]:
q4

                 district  documents_registered_rev
0                Adilabad                 324085539
1    Bhadradri Kothagudem                 241537476
2             Hanumakonda                2077808629
3               Hyderabad               10711890174
4                 Jagtial                 440627967
5                 Jangoan                 259887134
6        Jogulamba Gadwal                 272675969
7               Kamareddy                 379949388
8              Karimnagar                1068655123
9                 Khammam                1643522261
10  Kumurambheem Asifabad                  61025705
11            Mahabubabad                 257524461
12           Mahabubnagar                 893998095
13             Mancherial                 437644812
14                  Medak                 428017430
15     Medchal_Malkajgiri               18200892201
16                 Mulugu                 147262077
17           Nagarkurnool                 377760177
18               Nalgonda                1216066394
19             Narayanpet                 201723820
20                 Nirmal                 295357009
21              Nizamabad                1151056746
22             Peddapalli                 500011727
23       Rajanna Sircilla                 291933827
24             Rangareddy               31865475990
25             Sangareddy                6344385117
26               Siddipet                 734228894
27               Suryapet                 777314773
28              Vikarabad                 373227540
29             Wanaparthy                 306686397
30               Warangal                 174157126
31    Yadadri Bhuvanagiri                1619590278

In [51]:
fy_2021_grouped

,district,documents_registered_cnt,documents_registered_rev,estamps_challans_cnt,estamps_challans_rev
0,Adilabad,11031,324085539,13337,332597037
1,Bhadradri Kothagudem,9175,241537476,10261,254379427
2,Hanumakonda,42217,2077808629,46463,2112813388
3,Hyderabad,54277,10711890174,59519,10893677949
4,Jagtial,15698,440627967,16332,443715297
5,Jangoan,11756,259887134,12294,261658853
6,Jogulamba Gadwal,16735,272675969,17288,272076616
7,Kamareddy,19080,379949388,20062,380467770
8,Karimnagar,30547,1068655123,31737,1078423581
9,Khammam,44191,1643522261,46533,1644624288
10,Kumurambheem Asifabad,2321,61025705,2416,58294715
11,Mahabubabad,11685,257524461,12887,264393331
12,Mahabubnagar,30100,893998095,31260,899612434
13,Mancherial,16764,437644812,17847,444256231
14,Medak,9578,428017430,10126,482267731
15,Medchal_Malkajgiri,148290,18200892201,157552,18747892104
16,Mulugu,7841,147262077,8260,148856779
17,Nagarkurnool,24069,377760177,25012,378375339
18,Nalgonda,50882,1216066394,52572,1221278894
19,Narayanpet,8324,201723820,8699,205291521
20,Nirmal,14725,295357009,15156,293878065
21,Nizamabad,45051,1151056746,48861,1165209994
22,Peddapalli,13351,500011727,14270,508023769
23,Rajanna Sircilla,16463,291933827,16789,294316478
24,Rangareddy,221446,31865475990,235763,32332939769
25,Sangareddy,63764,6344385117,69505,6522436259
26,Siddipet,35496,734228894,36768,746741914
27,Suryapet,30738,777314773,32906,792850936
28,Vikarabad,14839,373227540,15486,387426499
29,Wanaparthy,17282,306686397,17997,306488316
30,Warangal,7885,174157126,8293,173457579
31,Yadadri Bhuvanagiri,58979,1619590278,61727,1616599565

In [52]:
fy_2022_grouped['total_revenue'] = fy_2022_grouped['documents_registered_rev'] + fy_2022_grouped['estamps_challans_rev']

In [53]:
q4 = fy_2022_grouped.copy(deep=True)
del q4['estamps_challans_cnt']
del q4['documents_registered_cnt']
del q4['documents_registered_rev']
del q4['estamps_challans_rev']
del q4['stamp_doc_ratio']
q4

                 district  total_revenue
0                Adilabad      787246889
1    Bhadradri Kothagudem      578986575
2             Hanumakonda     5664095431
3               Hyderabad    28640327473
4                 Jagtial     1264515558
5                 Jangoan      959496571
6        Jogulamba Gadwal      660888642
7               Kamareddy      950823592
8              Karimnagar     3106003204
9                 Khammam     3973867853
10  Kumurambheem Asifabad      150357199
11            Mahabubabad      803650312
12           Mahabubnagar     2147772902
13             Mancherial     1310620856
14                  Medak     1358313769
15     Medchal_Malkajgiri    47639706838
16                 Mulugu      438142770
17           Nagarkurnool     1004117412
18               Nalgonda     2749372025
19             Narayanpet      523385769
20                 Nirmal      684262723
21              Nizamabad     2891119834
22             Peddapalli     1229064287
23       Rajanna Sircilla      908530352
24             Rangareddy    76047108564
25             Sangareddy    16532805623
26               Siddipet     2023763688
27               Suryapet     2050904064
28              Vikarabad     1032720913
29             Wanaparthy      876928910
30               Warangal      503634678
31    Yadadri Bhuvanagiri     4352751270

In [54]:
q4.to_csv('/content/drive/MyDrive/q4.csv',index=False)